#!/bin/bash


#Project - 4
#Creating Local Users


#Requirement

#
#
#Script should be executed with root user else exit with status 1 and error message.
#Script will take 1st argument as user and rest will be treated as comment.
#Auto generate password for the user.
#Upon successful execution of script, display the following:
      #username: <username>
      #password: <auto-generated-password>
      #host: <host_name>



#Scripting begins

#Steps

#Script should be executed with sudo/root access.
if [[ ${UID} -ne 0 ]]
then 
	echo "Permission denied!"
	echo "Root access required"
	exit 1
fi

#User should provide atleast one argument as username else guide him

if [[ ${#} -eq 0 ]] 
then
	echo "usage: ${0} USER_NAME [COMMENT]..."
	echo "Create a user with name USER_NAME and comments field of COMMENT"
	exit 1
fi

# Store first argument as user name
USER_NAME="${1}"

# Removing first argument by Shifting
shift

#In case of more than one argument, stroe it as account comments
COMMENT="${@}"


#Create a Password
PASSWORD=$(date +%s%N)


#Create the user
useradd -c "$COMMENT" -m $USER_NAME


#Check if user is successfully created or not 

if [[ ${?} -ne 0 ]]
then
	echo "The Accound could not be created!"
	exit 1
fi

#Set the password for the user.

#first way

#echo -e "$PASSWORD\n$PASSWORD" | passwd "$USER_NAME"

#second way

echo "$USER_NAME:$PASSWORD" | chpasswd



#Check if password is successfully set or not


if [[ ${?} -ne 0 ]] 
then
	echo "Password could not be set"
	exit 1
fi


#Force password change on first login

passwd -e $USER_NAME

#Display the username, password and the host where it was created.

echo 
echo "Username: $USER_NAME"
echo 
echo "Password: $PASSWORD"
echo
echo "Host: $(hostname)"

#Also creating and storing the credential in a file

#taking reference of present working directory
CRE_DIR=$(pwd)

#if user credential directory is not present

if [[ ! -d $CRE_DIR/user_cre ]]
then
	mkdir $CRE_DIR/user_cre
	echo "User directory is created!"
fi

#Now creating the file and append the credential in file and also move to specified directory

#creating file
touch $USER_NAME

#Appending username and password in the file
echo "USER-NAME: $USER_NAME" >> $USER_NAME
echo "PASSWORD: $PASSWORD" >> $USER_NAME

#move the file to user_cre directory
mv $USER_NAME $CRE_DIR/user_cre 
echo "File Successfully created and stored!"


################################END##################################
